Update README.md
sclorg/django-ex pull request #202
Opened 2023-05-29 12:13 UTC by BeataSolitudo

2023-05-29 12:14 UTC, BeataSolitudo commented
Update readme

2023-05-30 05:24 UTC, frenzymadness requested changes
I've found one typo. Could you please fix it?

2023-05-30 05:24 UTC, frenzymadness commented on README.md
> +3. Fork this repo and clone your fork: Fork this repo and clone your fork. Make sure that you are in the right branch.
The first sentence is twice there.

2023-05-31 10:31 UTC, frenzymadness approved these changes
Looks good to me.

2023-05-31 10:31 UTC, merged